[package]
name = "ipshifter"
version = "0.1.3"
edition = "2021"

[dependencies]
clap = {version = "4.5.35", features = ["derive"]}
colored = "3.0.0"
nix = { version = "0.29.0", features = ["user"] }
signal-hook = "0.3"
