name: Build & Publish All Package

on:
  push:
    tags:
      - "v*"

jobs:
  setup-dir:
    runs-on: ubuntu-latest
    steps:

    - name: Create repo dir
      run: mkdir repo
    
    - name: Upload repo dir
      uses: actions/upload-artifact@v4
      with:
        name: artifact-repo
        path: repo
    
  call-deb-build:
    uses: ./.github/workflows/deb-build.yml
    needs: setup-dir
    with:
      artifact-name: artifact-repo
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  
  deploy:
    runs-on: ubuntu-latest
    needs: call-deb-build
    steps:
      - name: Download repo dir
        uses: actions/download-artifact@v4
        with:
          name: artifact-repo
          path: repo

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.dir }}
          publish_branch: gh-pages
          force_orphan: true